Rustcandy/add migrate
milkyway-labs/ica-oracle pull request #2
Opened 2024-03-20 09:14 UTC by rustcandy

Migrate function has been added & teseted on the testnet

2024-03-20 14:16 UTC, hallazzang requested changes

2024-03-20 14:16 UTC, hallazzang commented on src/msg.rs
> +#[derive(Serialize, Deserialize, JsonSchema)]
Why don't we just use `#[cw_serde]` here?

2024-03-20 14:36 UTC, RiccardoM approved these changes
Looks good to me. I got the same comment of Hanjun but aside from that nothing to point out

2024-03-21 02:49 UTC, hallazzang approved these changes
LGTM

2024-03-21 08:15 UTC, merged